spring.application.name=TestApp

#JPA & Hibernate Properties
spring.jpa.hibernate.ddl-auto=create
spring.h2.console.enabled=true

#DB Properties
spring.datasource.url=jdbc:mysql://localhost:3306/ProdDB?createDatabaseIfNotExist=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=Abhishek@1519#

my-variable=prod