spring.application.name=SignupLogin

#JPA & Hibernate Properties
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#MYSQL Properties
spring.datasource.url=jdbc:mysql://localhost:3306/prod_ready_features?createDatabaseIfNotExist=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=Abhishek@1519#

#Changing Server Port
server.port=9000

#Setting Third Party API Base URL
employeeService.base.url=http://localhost:8080/

#Logging Properties
logging.level.com.spring.SignupLogin.clients=TRACE
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{36} - %msg%n
logging.config=classpath:logback-spring.xml

#Actuator Configuration
management.endpoints.web.exposure.include=*
management.info.env.enabled=true
info.app.author=Abhishek Layek
info.app.version=1.0.0
management.endpoint.env.show-values=always
management.info.build.enabled=true
management.info.git.enabled=true
management.info.java.enabled=true
management.info.os.enabled=true

#JWT
jwt.secretkey=8f4d2b7c9e1a63f5d0b84c17a92ef63bc4d9a1e57f08b3266cb7d4f9a0e18c52


deploy.env = development


#OAuth2 Configuration
spring.security.oauth2.client.registration.google.client-id=<Your Google OAuth2 Client Id>
spring.security.oauth2.client.registration.google.client-secret=<Your Google OAuth2 Client Secret>