spring.application.name=SpringMVC
spring.jpa.hibernate.ddl-auto=create
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:file:D:/Spring Boot/2. Spring Boot MVC and RESTful APIs/2.5. PUT, PATCH, DELETE Mappings/employeeDB
spring.datasource.username=h2DB
spring.datasource.password=Abhi@2001